// Generated by @sloopworks/swip-schema — DO NOT EDIT.
package works.sloop.swip.schema.latertext

object LatertextAnonymousSafe {
    val schemas: Set<String> = setOf(
        "swip:event:app_backgrounded:1",
        "swip:event:app_foregrounded:1",
        "swip:event:latertext_schedule_changed:1",
        "swip:event:latertext_schedule_saved:1",
        "swip:event:latertext_screen_viewed:1",
        "swip:event:screen_view:1",
    )
}
