// Generated by @sloopworks/swip-schema — DO NOT EDIT. Source: schemas/latertext/ YAML (ADR-0004).
@file:Suppress("unused")

package works.sloop.swip.schema.latertext

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonPrimitive
import works.sloop.swip.SwipEvent

@Serializable
data class LatertextScheduleChanged(
    val operation: Operation,
) : SwipEvent {

    override val schema: String get() = "swip:event:latertext_schedule_changed:1"

    override val props: Map<String, JsonElement?>
        get() = mapOf(
            "operation" to JsonPrimitive(operation.name.lowercase()),
        )

    @Serializable
    enum class Operation {
        @SerialName("pause") PAUSE,
        @SerialName("resume") RESUME,
        @SerialName("delete") DELETE,
        @SerialName("pause_all") PAUSE_ALL,
        @SerialName("resume_all") RESUME_ALL,
    }
}

@Serializable
data class LatertextScheduleSaved(
    val outcome: Outcome,
    val frequency: Frequency,
    @SerialName("has_media") val hasMedia: Boolean,
) : SwipEvent {

    override val schema: String get() = "swip:event:latertext_schedule_saved:1"

    override val props: Map<String, JsonElement?>
        get() = mapOf(
            "outcome" to JsonPrimitive(outcome.name.lowercase()),
            "frequency" to JsonPrimitive(frequency.name.lowercase()),
            "has_media" to JsonPrimitive(hasMedia),
        )

    @Serializable
    enum class Outcome {
        @SerialName("saved") SAVED,
        @SerialName("failed") FAILED,
    }
    @Serializable
    enum class Frequency {
        @SerialName("once") ONCE,
        @SerialName("daily") DAILY,
        @SerialName("weekly") WEEKLY,
        @SerialName("monthly") MONTHLY,
    }
}

@Serializable
data class LatertextScreenViewed(
    val screen: Screen,
) : SwipEvent {

    override val schema: String get() = "swip:event:latertext_screen_viewed:1"

    override val props: Map<String, JsonElement?>
        get() = mapOf(
            "screen" to JsonPrimitive(screen.name.lowercase()),
        )

    @Serializable
    enum class Screen {
        @SerialName("upcoming") UPCOMING,
        @SerialName("history") HISTORY,
        @SerialName("settings") SETTINGS,
        @SerialName("composer") COMPOSER,
        @SerialName("schedule_editor") SCHEDULE_EDITOR,
        @SerialName("detail") DETAIL,
    }
}
