// Generated by @sloopworks/swip-schema — DO NOT EDIT. Source: registry/products/latertext.yaml (ADR-0019).
package works.sloop.swip.schema.latertext

import works.sloop.swip.CollectionMode
import works.sloop.swip.DeliveryMode
import works.sloop.swip.SwipInitConfig
import works.sloop.swip.SwipPlatformDeps
import works.sloop.swip.SwipStorage
import works.sloop.swip.channel.ChannelSignals
import works.sloop.swip.config.ConfigKeyInfo
import works.sloop.swip.config.ConfigKeySpec
import works.sloop.swip.pipeline.AnalyticsTransport
import works.sloop.swip.pipeline.NoOpTransport
import works.sloop.swip.pipeline.PersistentQueue

object LatertextSwip {
    fun androidDev(): SwipInitConfig = SwipInitConfig(
        product = "latertext",
        tenant = "sloopworks",
        sourceKey = "swip_pub_latertext_android_dev",
        stableEndpoint = "",
        discovery = false,
        deliveryMode = DeliveryMode.LOCAL_ONLY,
        modules = listOf("analytics"),
        crashVendor = "none",
        channel = "dev",
    )

    fun platformDeps(
        transport: AnalyticsTransport = NoOpTransport(),
        storage: SwipStorage,
        appVersion: String,
        os: String,
        nowMs: () -> Long,
        monotonicNowMs: () -> Long,
        random: () -> Double,
        persistence: PersistentQueue? = null,
        ulid: (() -> String)? = null,
        flushIntervalMs: Long = 30_000,
        initialMode: CollectionMode = CollectionMode.OFF,
        channelSignals: ChannelSignals = ChannelSignals(),
        configDefaults: Map<String, ConfigKeySpec> = emptyMap(),
        authoredCatalog: List<ConfigKeyInfo> = emptyList(),
    ): SwipPlatformDeps = SwipPlatformDeps(
        transport = transport,
        storage = storage,
        appVersion = appVersion,
        os = os,
        nowMs = nowMs,
        monotonicNowMs = monotonicNowMs,
        random = random,
        persistence = persistence,
        ulid = ulid,
        flushIntervalMs = flushIntervalMs,
        criticalSchemas = LatertextCritical.schemas,
        anonymousSafeSchemas = LatertextAnonymousSafe.schemas,
        pseudonymousStrip = LatertextPseudonymousStrip.fields,
        initialMode = initialMode,
        channelSignals = channelSignals,
        configDefaults = configDefaults,
        authoredCatalog = authoredCatalog,
    )
}
