// Generated by @sloopworks/swip-schema — DO NOT EDIT. Source: schemas/latertext/ (ADR-0018).
package works.sloop.swip.schema.latertext

/** schema id → fields stripped in PSEUDONYMOUS collection mode (docs/13 §2). */
object LatertextPseudonymousStrip {
    val fields: Map<String, Set<String>> = emptyMap()
}
